### ISSUE TITLE
OSError: [Errno 107] Transport endpoint is not connected

### ISSUE THREAD

**Issue by Yuuki2012** [effigies/BitTornado#30]
```Python
Traceback (most recent call last):
  File "/home/BitTornado/BitTornado/Network/RawServer.py", line 120, in listen_forever
    self.sockethandler.handle_events(events)
  File "/home/BitTornado/BitTornado/Network/SocketHandler.py", line 293, in handle_events
    s.handler.data_came_in(s, data)
  File "/home/BitTornado/BitTornado/Tracker/HTTPHandler.py", line 148, in data_came_in
    if not c.data_came_in(data) and not c.closed:
  File "/home/BitTornado/BitTornado/Tracker/HTTPHandler.py", line 35, in data_came_in
    self.next_func = self.next_func(val.decode())
  File "/home/BitTornado/BitTornado/Tracker/HTTPHandler.py", line 67, in read_header
    r = self.handler.getfunc(self, self.path, self.headers)
  File "/home/BitTornado/BitTornado/Tracker/track.py", line 1005, in get
    rsize = self.add_data(infohash, event, ip, paramslist)
  File "/home/BitTornado/BitTornado/Tracker/track.py", line 795, in add_data
    del x[y][myid]
KeyError: b'-UT3000->c-N\xce\x10o>z\xad\xb2\xae'
Traceback (most recent call last):
  File "/home/BitTornado/BitTornado/Network/SocketHandler.py", line 293, in handle_events
    s.handler.data_came_in(s, data)
  File "/home/BitTornado/BitTornado/Tracker/HTTPHandler.py", line 148, in data_came_in
    if not c.data_came_in(data) and not c.closed:
  File "/home/BitTornado/BitTornado/Tracker/HTTPHandler.py", line 35, in data_came_in
    self.next_func = self.next_func(val.decode())
  File "/home/BitTornado/BitTornado/Tracker/HTTPHandler.py", line 69, in read_header
    self.answer(r)
  File "/home/BitTornado/BitTornado/Tracker/HTTPHandler.py", line 122, in answer
    self.connection.shutdown(1)
  File "/home/BitTornado/BitTornado/Network/SocketHandler.py", line 64, in shutdown
    self.socket.shutdown(val)
OSError: [Errno 107] Transport endpoint is not connected
```

During handling of the above exception, another exception occurred:

```Python
Traceback (most recent call last):
  File "/home/BitTornado/BitTornado/Network/RawServer.py", line 120, in listen_forever
    self.sockethandler.handle_events(events)
  File "/home/BitTornado/BitTornado/Network/SocketHandler.py", line 295, in handle_events
    if e[0] != EWOULDBLOCK:
TypeError: 'OSError' object is not subscriptable
```

This is a big one, I'm not sure how it occured because I was asleep, but might have something to do with scraping...?

**Comment by effigies** [comment]
Thanks for all the reports! Three tracebacks will probably take a little time to track down and fix. Started an issue_30 branch I'll work on (no changes yet).

**Comment by Yuuki2012** [comment]
Sure thing ^^ at least this is not a dead project, I'm glad I can be of some help! :)

**Comment by Yuuki2012** [comment]
I figured that when this error occurs, peers are unable to connect, pretty much the same as the tracker being offline -- I can't scrape either.

**Comment by effigies** [comment]
Okay. So it looks like this is probably related to #23, which may be a failure to register clients. So removing a client will fail because it's not there.

Either way, there are also some bugs here that aren't that. Updated issue_30 to take care of these tracebacks. Will start a PR.

But yeah, need to dig in and figure out what's happening here.

**Comment by effigies** [comment]
Can you check issue_30, now? I pushed a fix to a bug I accidentally introduced in #28, which caused NAT'd peers that are crypto-enabled to push the tracker into an infinite loop.

**Comment by Yuuki2012** [comment]
Okay, let's see ^^

**Comment by effigies** [comment]
Any luck?

**Comment by Yuuki2012** [comment]
I haven't ran into the problem for now, guess you can close it. ^^ it's been running fine ever since.
