### ISSUE TITLE
ImportError: cannot import name HTTPSConnection

### ISSUE THREAD

**Issue by yang502** [effigies/BitTornado#34]
I am using the  master branch on Python3.5 and Python3.3，both show the Error infos.
when i run tracker , it shows as follows:

[root@bogon BitTornado]# python bttrack.py --port 6969 --dfile dstate
Traceback (most recent call last):
  File "bttrack.py", line 7, in <module>
    from BitTornado.Tracker.track import track
  File "/root/BitTornado/BitTornado/Tracker/track.py", line 16, in <module>
    from .T2T import T2TList
  File "/root/BitTornado/BitTornado/Tracker/T2T.py", line 4, in <module>
    from BitTornado.Client.Announce import Announcer
  File "/root/BitTornado/BitTornado/Client/Announce.py", line 14, in <module>
    from BitTornado.Network.Stream import SharedStream
  File "/root/BitTornado/BitTornado/Network/Stream.py", line 17, in <module>
    from http.client import HTTPConnection, HTTPSConnection, HTTPException
ImportError: cannot import name HTTPSConnection

**Comment by effigies** [comment]
Ah, you probably don't have the ssl library. The issue_34 branch should fix it.

To verify, though, can you try `import ssl` from a python prompt?

**Comment by yang502** [comment]
Thanks for your reply!
1、I try import ssl from a python prompt.It prompt without _ssl module.So I install ssl and reconfigure      Python.Then retry to run tracker,it shows another problem:

Traceback (most recent call last):
  File "bttrack.py", line 7, in <module>
    from BitTornado.Tracker.track import track
  File "/root/BitTornado/BitTornado/Tracker/track.py", line 16, in <module>
    from .T2T import T2TList
  File "/root/BitTornado/BitTornado/Tracker/T2T.py", line 4, in <module>
    from BitTornado.Client.Announce import Announcer
  File "/root/BitTornado/BitTornado/Client/Announce.py", line 14, in <module>
    from BitTornado.Network.Stream import SharedStream
  File "/root/BitTornado/BitTornado/Network/Stream.py", line 220, in <module>
    class ShareHTTPS(ShareHTTP):
  File "/root/BitTornado/BitTornado/Network/Stream.py", line 229, in ShareHTTPS
    SSLCONTEXT = ssl.create_default_context()
AttributeError: 'module' object has no attribute 'create_default_context'

2、Is master branch supporte all the Python3.x version？
  The problem I encountered is because of the wrong Python environment ?

**Comment by yang502** [comment]
Now I using the master branch on Python3.5.2 , and updated my local Stream.py file.
I can run the tracker successfull.

My torrent file is :  
metainfo file.: VMGL_3D_win7.img.torrent
info hash.....: 263b90dc18c5a0c53d07d9c3e7335b4d0d84062c
file name.....: VMGL_3D_win7.img
file size.....: 720764928 (1374 * 524288 + 393216)
announce url..: http://172.21.36.99:6969/announce

But when I want  to download the torrent file ,it shows as follows:
ERROR:
http seed url not http: 

saving:         VMGL_3D_win7.img (687.4 MB)
percent done:   0.0
time left:      
download to:    /root/BitTornado/VMGL_3D_win7.img
download rate:  
upload rate:    
share rating:   
seed status:    
peer status:    
Traceback (most recent call last):
  File "btdownloadheadless.py", line 224, in <module>
    run(sys.argv[1:])
  File "btdownloadheadless.py", line 192, in run
    dow.startRerequester()
  File "/root/BitTornado/BitTornado/Client/download_bt1.py", line 578, in startRerequester
    announcers = urls_to_announcers(tracker_urls, **kwargs)
  File "/root/BitTornado/BitTornado/Client/Announce.py", line 436, in urls_to_announcers
    for tier in trackerlist]
  File "/root/BitTornado/BitTornado/Client/Announce.py", line 436, in <listcomp>
    for tier in trackerlist]
  File "/root/BitTornado/BitTornado/Client/Announce.py", line 435, in <listcomp>
    return [[Announcer(url, *args, **kwargs) for url in tier]
  File "/root/BitTornado/BitTornado/Client/Announce.py", line 98, in __new__
    return cls.subclasses[scheme](tracker_url, port, *args, **kwargs)
KeyError: ''

**Comment by effigies** [comment]
Can you open a new issue? Sorry, but this is a different problem, and I'm closing this issue in #35.
