### ISSUE TITLE
KeyError: b'-UT2210-\xd6b\xd8\xbf\xe0\xcf\xc1\xe9E\x94\x1d\xc6'

### ISSUE THREAD

**Issue by Yuuki2012** [effigies/BitTornado#38]
```Python
Traceback (most recent call last):
  File "/home/BitTornado/BitTornado/Network/RawServer.py", line 120, in listen_forever
    self.sockethandler.handle_events(events)
  File "/home/BitTornado/BitTornado/Network/SocketHandler.py", line 296, in handle_events
    s.handler.data_came_in(s, data)
  File "/home/BitTornado/BitTornado/Tracker/HTTPHandler.py", line 148, in data_came_in
    if not c.data_came_in(data) and not c.closed:
  File "/home/BitTornado/BitTornado/Tracker/HTTPHandler.py", line 35, in data_came_in
    self.next_func = self.next_func(val.decode())
  File "/home/BitTornado/BitTornado/Tracker/HTTPHandler.py", line 67, in read_header
    r = self.handler.getfunc(self, self.path, self.headers)
  File "/home/BitTornado/BitTornado/Tracker/track.py", line 1009, in get
    rsize = self.add_data(infohash, event, ip, paramslist)
  File "/home/BitTornado/BitTornado/Tracker/track.py", line 799, in add_data
    del x[y][myid]
KeyError: b'-UT2210-\xd6b\xd8\xbf\xe0\xcf\xc1\xe9E\x94\x1d\xc6'
```

I think this is related to Issue #30, is this the encrypted peers thing again? And isn't UT2210 uTorrent 2.2.1.0?

Sorry I keep poking you with Issues :smile:

**Comment by effigies** [comment]
I think you might not be working with the most recent master? Just looking at the line numbers, `del x[y][myid]` is on [line 800](https://github.com/effigies/BitTornado/blob/master/BitTornado/Tracker/track.py#L800), not 799.

Try a `git pull`, and see if that fixes things.

And yes, UT2210 is most likely uTorrent. If they have a version 2.2.1.0, that seems perfectly reasonable.

**Comment by effigies** [comment]
And no worries about the pokes. It's been nice to look at this project again, and hopefully I'll get everything back to working shape.

**Comment by Yuuki2012** [comment]
Haven't seen this error for the past 3 days, but I do have a new one -- the tracker isn't starting either, see the new issue.

**Comment by effigies** [comment]
Okay, I'm closing this. Just re-open it (or #30) if it comes back up. No need to start a new issue.
