### ISSUE TITLE
codec can't decode byte 0xa0 in position 13

### ISSUE THREAD

**Issue by Yuuki2012** [effigies/BitTornado#51]
```Python
TypeError: 'str' does not support the buffer interface
Traceback (most recent call last):
  File "/home/BitTornado/BitTornado/Network/RawServer.py", line 120, in listen_forever
    self.sockethandler.handle_events(events)
  File "/home/BitTornado/BitTornado/Network/SocketHandler.py", line 296, in handle_events
    s.handler.data_came_in(s, data)
  File "/home/BitTornado/BitTornado/Tracker/HTTPHandler.py", line 148, in data_came_in
    if not c.data_came_in(data) and not c.closed:
  File "/home/BitTornado/BitTornado/Tracker/HTTPHandler.py", line 35, in data_came_in
    self.next_func = self.next_func(val.decode())
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa0 in position 13: invalid start byte
Traceback (most recent call last):
  File "/home/BitTornado/BitTornado/Network/RawServer.py", line 120, in listen_forever
    self.sockethandler.handle_events(events)
  File "/home/BitTornado/BitTornado/Network/SocketHandler.py", line 296, in handle_events
    s.handler.data_came_in(s, data)
  File "/home/BitTornado/BitTornado/Tracker/HTTPHandler.py", line 148, in data_came_in
    if not c.data_came_in(data) and not c.closed:
  File "/home/BitTornado/BitTornado/Tracker/HTTPHandler.py", line 35, in data_came_in
    self.next_func = self.next_func(val.decode())
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa0 in position 13: invalid start byte
```

Hi again ^^ I have a new error for you, I'm assuming it's caused by a '!' in the filename, I'm currently trying to test this. (basically moving the file out of the parse directory and check if the error still appears)

**Comment by effigies** [comment]
Hmm. I'll have a look. Thanks for the report.

**Comment by effigies** [comment]
What branch/commit are you using?

**Comment by Yuuki2012** [comment]
The latest one I should be using (with the latest error fix I've reported)

**Comment by Yuuki2012** [comment]
Changing the
```python
self.next_func = self.next_func(val.decode())
```
to
```python
self.next_func = self.next_func(val.decode('cp1252'))
```
on Tracker/HTTPHandler.py seems to have worked, I'm not sure if I should be using cp1252 but it fixed the crashing at least. (for now)

**Comment by effigies** [comment]
I suspect that works only because `0xA0'` is a valid code point in cp1252, not that information is actually being transmitted in cp1252.

Is it a specific `.torrent` file that's causing this issue? If you could share that, I may be able to reproduce and track down the bug.

**Comment by Yuuki2012** [comment]
I'm not sure which torrent it is (or if it's even a torrent causing it), but SHOULD be one of these:
http://www.nyaa.se/?page=download&tid=851191
http://www.nyaa.se/?page=download&tid=851185
http://www.nyaa.se/?page=download&tid=851095
http://www.nyaa.se/?page=download&tid=851203
those were uploaded before the crashes happened
