### ISSUE TITLE
Python3.6 can't work

### ISSUE THREAD

**Issue by alahoo** [effigies/BitTornado#55]
Python3.6 can't work
python btdownloadcurses.py --metafile 1.zip.torrent --saveas 1.zip
 ------------------------------------------------------------------------------------------------------------------
| file:     1.zip
| size:     39.08MiB
| dest:     /data/data/omcs/web/upfiles/omsa/1.zip
| progress: _______________________________________________________________________________________________________________
| status:   download succeeded! 
| dl speed: ---
| ul speed: 0.0 KB/s
| sharing:  0.000  (0.0 MB up / 0.0 MB down)
| seeds:    0 seen recently, plus 0.000 distributed copies
| peers:    0 seen now, 0.0% done at 0.0 kB/s

#################################################################

python  btdownloadheadless.py --metafile 1.zip.torrent --saveas /tmp/1.zip
 ------------------------------------------------------------------------------------------------------------------
| file:     1.zip
| size:     39.08MiB
| dest:     /tmp/1.zip
| progress: _______________________________________________________________________________________________________________
| status:   connecting to peers (0.0%)
| dl speed: 0.0 KB/s
| ul speed: 0.0 KB/s
| sharing:  0.000  (0.0 MB up / 0.0 MB down)
| seeds:    0 seen now, plus 0.000 distributed copies
| peers:    0 seen now, 0.0% done at 0.0 kB/s
|

**Comment by alahoo** [comment]
# python btdownloadcurses.py --metafile 1.zip.torrent --saveas /tmp/1.zip --ip 192.168.1.12
These errors occurred during execution:
[10:25:57] Traceback (most recent call last):
  File "/data/data/omcs/commands/omcs_bt/BitTornado/Client/Rerequester.py", line 220, in _rerequest_single
    **kwargs)
  File "/data/data/omcs/commands/omcs_bt/BitTornado/Client/Announce.py", line 392, in announce
    query = str(RequestURL(options))
  File "/data/data/omcs/commands/omcs_bt/BitTornado/Types/collections.py", line 167, in __init__
    self.update(*args, **kwargs)
  File "/data/data/omcs/commands/omcs_bt/BitTornado/Types/collections.py", line 208, in update
    self[key] = val
  File "/data/data/omcs/commands/omcs_bt/BitTornado/Types/collections.py", line 188, in __setitem__
    raise KeyError('Invalid key: ' + key)
KeyError: 'Invalid key: ip'
