### ISSUE TITLE
KeyError: 'Invalid key: attr'

### ISSUE THREAD

**Issue by tikkel** [effigies/BitTornado#59]
Hi,
after i had installed (setup.py --install -f) under CentOS7 and python3.4.9, comes this when i will start the tacker:

 /usr/bin/bttrack.py

Traceback (most recent call last):
  File "/usr/bin/bttrack.py", line 7, in <module>
    from BitTornado.Tracker.track import track
ImportError: No module named 'BitTornado.Tracker'

Can anybody help me? Is there anywhere a ready RPM package? I am not a developer...
Greetings from Marko

**Comment by tikkel** [comment]
... ok, it is a rights problem. After sudoing bttrack.py starts:

 sudo /usr/bin/bttrack.py --port 6969 --dfile /var/lib/bittornado/bttrack.state

**Comment by tikkel** [comment]
... but there is the next problem. I want the "--allowed_dir" option. When i starts, comes this Errors:

 sudo /usr/bin/bttrack.py --port 6969 --dfile /var/lib/bittornado/bttrack.state --allowed_dir /var/www/blitz/torrents/   **warning** Error updating allowed torrents. Reparsing.
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/BitTornado/Tracker/track.py", line 1104, in parse_allowed
    [".torrent"])
  File "/usr/lib/python3.4/site-packages/BitTornado/Application/parsedir.py", line 81, in parsedir
    torrentinfo, infohash = parse_torrent(path, return_metainfo)
  File "/usr/lib/python3.4/site-packages/BitTornado/Application/parsedir.py", line 163, in parse_torrent
    data = MetaInfo.read(path)
  File "/usr/lib/python3.4/site-packages/BitTornado/Meta/bencode.py", line 198, in read
    **kwargs)
  File "/usr/lib/python3.4/site-packages/BitTornado/Meta/Info.py", line 410, in __init__
    super(MetaInfo, self).__init__(*args, **kwargs)
  File "/usr/lib/python3.4/site-packages/BitTornado/Types/collections.py", line 167, in __init__
    self.update(*args, **kwargs)
  File "/usr/lib/python3.4/site-packages/BitTornado/Types/collections.py", line 205, in update
    self[key] = arg[key]
  File "/usr/lib/python3.4/site-packages/BitTornado/Types/collections.py", line 183, in __setitem__
    val = self.typemap[key](val)
  File "/usr/lib/python3.4/site-packages/BitTornado/Meta/Info.py", line 228, in __init__
    self['files'] = params['files']
  File "/usr/lib/python3.4/site-packages/BitTornado/Types/collections.py", line 183, in __setitem__
    val = self.typemap[key](val)
  File "/usr/lib/python3.4/site-packages/BitTornado/Types/collections.py", line 62, in new_method
    for sub in arg)
  File "/usr/lib/python3.4/site-packages/BitTornado/Types/collections.py", line 62, in <genexpr>
    for sub in arg)
  File "/usr/lib/python3.4/site-packages/BitTornado/Types/collections.py", line 22, in normalize
    return targettype(arg)
  File "/usr/lib/python3.4/site-packages/BitTornado/Types/collections.py", line 167, in __init__
    self.update(*args, **kwargs)
  File "/usr/lib/python3.4/site-packages/BitTornado/Types/collections.py", line 205, in update
    self[key] = arg[key]
  File "/usr/lib/python3.4/site-packages/BitTornado/Types/collections.py", line 188, in __setitem__
    raise KeyError('Invalid key: ' + key)
KeyError: 'Invalid key: attr'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/bttrack.py", line 24, in <module>
    track(sys.argv[1:])
  File "/usr/lib/python3.4/site-packages/BitTornado/Tracker/track.py", line 1199, in track
    t = Tracker(config, r)
  File "/usr/lib/python3.4/site-packages/BitTornado/Tracker/track.py", line 412, in __init__
    self.parse_allowed()
  File "/usr/lib/python3.4/site-packages/BitTornado/Tracker/track.py", line 1109, in parse_allowed
    [".torrent"])
  File "/usr/lib/python3.4/site-packages/BitTornado/Application/parsedir.py", line 81, in parsedir
    torrentinfo, infohash = parse_torrent(path, return_metainfo)
  File "/usr/lib/python3.4/site-packages/BitTornado/Application/parsedir.py", line 163, in parse_torrent
    data = MetaInfo.read(path)
  File "/usr/lib/python3.4/site-packages/BitTornado/Meta/bencode.py", line 198, in read
    **kwargs)
  File "/usr/lib/python3.4/site-packages/BitTornado/Meta/Info.py", line 410, in __init__
    super(MetaInfo, self).__init__(*args, **kwargs)
  File "/usr/lib/python3.4/site-packages/BitTornado/Types/collections.py", line 167, in __init__
    self.update(*args, **kwargs)
  File "/usr/lib/python3.4/site-packages/BitTornado/Types/collections.py", line 205, in update
    self[key] = arg[key]
  File "/usr/lib/python3.4/site-packages/BitTornado/Types/collections.py", line 183, in __setitem__
    val = self.typemap[key](val)
  File "/usr/lib/python3.4/site-packages/BitTornado/Meta/Info.py", line 228, in __init__
    self['files'] = params['files']
  File "/usr/lib/python3.4/site-packages/BitTornado/Types/collections.py", line 183, in __setitem__
    val = self.typemap[key](val)
  File "/usr/lib/python3.4/site-packages/BitTornado/Types/collections.py", line 62, in new_method
    for sub in arg)
  File "/usr/lib/python3.4/site-packages/BitTornado/Types/collections.py", line 62, in <genexpr>
    for sub in arg)
  File "/usr/lib/python3.4/site-packages/BitTornado/Types/collections.py", line 22, in normalize
    return targettype(arg)
  File "/usr/lib/python3.4/site-packages/BitTornado/Types/collections.py", line 167, in __init__
    self.update(*args, **kwargs)
  File "/usr/lib/python3.4/site-packages/BitTornado/Types/collections.py", line 205, in update
    self[key] = arg[key]
  File "/usr/lib/python3.4/site-packages/BitTornado/Types/collections.py", line 188, in __setitem__
    raise KeyError('Invalid key: ' + key)
KeyError: 'Invalid key: attr'
